#!/usr/bin/env bash
# Sub2API setup 1.0.0 — generated by scripts/build-sub2api-downloads.mjs
set -euo pipefail
command -v node >/dev/null 2>&1 || { echo 'Install Node.js 22+ first.' >&2; exit 1; }
umask 077
setup_dir=$(mktemp -d)
trap 'rm -f "$setup_dir/setup.mjs"; rmdir "$setup_dir"' EXIT
cat > "$setup_dir/setup.mjs" <<'SUB2API_NODE_SOURCE'
// Shared implementation embedded in both downloadable installers. Node.js 22+.
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { pathToFileURL } from 'node:url';
import { createInterface } from 'node:readline/promises';
import { Writable } from 'node:stream';
import { spawnSync } from 'node:child_process';

export const VERSION = '1.0.0';
export const DEFAULT_ORIGIN = 'https://sub2api.zhuoling.space';
const modelPattern = /^[a-zA-Z0-9][a-zA-Z0-9._:/-]{0,199}$/;
const sh = value => `'${value.replaceAll("'", "'\\''")}'`;
const ps = value => `'${value.replaceAll("'", "''")}'`;

export function validateConfig(input) {
  if (!['codex', 'claude'].includes(input.client)) throw new Error('Client must be codex or claude.');
  const url = new URL(input.baseUrl);
  if (url.origin !== DEFAULT_ORIGIN || url.username || url.password || url.search || url.hash || /%(?:2f|5c|2e)/i.test(url.pathname)) {
    throw new Error(`Use an HTTPS API base URL on ${DEFAULT_ORIGIN}.`);
  }
  let baseUrl = url.href.replace(/\/+$/, '');
  if (/\/(?:messages|responses|models)$/.test(baseUrl)) throw new Error('Enter the base URL, without /messages, /responses or /models.');
  if (input.client === 'codex' && url.pathname.replace(/\/+$/, '') === '') baseUrl += '/v1';
  if (input.client === 'claude' && /\/v1$/.test(baseUrl)) baseUrl = baseUrl.slice(0, -3);
  if (!modelPattern.test(input.model ?? '')) throw new Error('Enter a valid model ID from the console or model list.');
  if (typeof input.apiKey !== 'string' || !/^[\x21-\x7e]{8,4096}$/.test(input.apiKey)) throw new Error('API Key must contain 8–4096 printable non-space ASCII characters.');
  return { client: input.client, baseUrl, model: input.model, apiKey: input.apiKey };
}

export function apiUrl(config, resource) {
  const base = config.client === 'codex' ? config.baseUrl : `${config.baseUrl}/v1`;
  return `${base}/${resource}`;
}

export function headers(config) {
  return config.client === 'codex'
    ? { Authorization: `Bearer ${config.apiKey}` }
    : { 'x-api-key': config.apiKey, 'anthropic-version': '2023-06-01' };
}

export async function listModels(config, request = fetch) {
  const ids = new Set();
  let after = '';
  for (let page = 0; page < 10; page++) {
    const url = new URL(apiUrl(config, 'models'));
    if (after) url.searchParams.set('after_id', after);
    const response = await request(url, { headers: headers(config), redirect: 'error', signal: AbortSignal.timeout(15000) });
    if (!response.ok) throw new Error(`Model list HTTP ${response.status}. Check the key, group and API base URL.`);
    const body = await response.json();
    if (!Array.isArray(body.data)) throw new Error('The endpoint did not return a model list.');
    for (const model of body.data) if (modelPattern.test(model.id ?? '')) ids.add(model.id);
    if (config.client !== 'claude' || !body.has_more || typeof body.last_id !== 'string' || body.last_id === after) break;
    after = body.last_id;
  }
  return [...ids].sort();
}

export async function testRequest(config, request = fetch) {
  const codex = config.client === 'codex';
  const response = await request(apiUrl(config, codex ? 'responses' : 'messages'), {
    method: 'POST', redirect: 'error', signal: AbortSignal.timeout(45000),
    headers: { ...headers(config), 'Content-Type': 'application/json' },
    body: JSON.stringify(codex
      ? { model: config.model, input: 'Reply with OK.', max_output_tokens: 32, store: false }
      : { model: config.model, messages: [{ role: 'user', content: 'Reply with OK.' }], max_tokens: 32 }),
  });
  if (!response.ok) throw new Error(`Inference test HTTP ${response.status}. Check the console usage log and model permissions.`);
  const body = await response.json();
  if (body.error || (codex ? !Array.isArray(body.output) || body.status === 'failed' : !Array.isArray(body.content))) {
    throw new Error('The response did not contain the expected inference result.');
  }
}

export function launcher(config, windows) {
  const quote = windows ? ps : sh;
  const lines = windows ? ["$ErrorActionPreference = 'Stop'"] : ['#!/usr/bin/env bash', 'set -euo pipefail'];
  const env = config.client === 'codex' ? { SUB2API_API_KEY: config.apiKey } : {
    ANTHROPIC_BASE_URL: config.baseUrl, ANTHROPIC_AUTH_TOKEN: config.apiKey,
    ANTHROPIC_MODEL: config.model, ANTHROPIC_DEFAULT_OPUS_MODEL: config.model,
    ANTHROPIC_DEFAULT_SONNET_MODEL: config.model, ANTHROPIC_DEFAULT_HAIKU_MODEL: config.model,
    CLAUDE_CODE_SUBAGENT_MODEL: config.model,
  };
  // Claude's process inherits only the gateway credential/provider selection.
  const clear = config.client === 'claude' ? ['ANTHROPIC_API_KEY', 'CLAUDE_CODE_OAUTH_TOKEN', 'CLAUDE_CODE_USE_BEDROCK', 'CLAUDE_CODE_USE_VERTEX', 'CLAUDE_CODE_USE_FOUNDRY'] : [];
  if (windows) {
    lines.push('$saved = @{}');
    for (const name of [...Object.keys(env), ...clear]) lines.push(`$saved[${ps(name)}] = [Environment]::GetEnvironmentVariable(${ps(name)}, 'Process')`);
    lines.push('try {');
  }
  for (const name of clear) lines.push(windows ? `Remove-Item Env:${name} -ErrorAction SilentlyContinue` : `unset ${name}`);
  for (const [name, value] of Object.entries(env)) lines.push(windows ? `$env:${name} = ${quote(value)}` : `export ${name}=${quote(value)}`);
  const args = config.client === 'codex' ? [
    '-c', 'model_provider="sub2api"', '-c', `model=${JSON.stringify(config.model)}`,
    '-c', 'model_providers.sub2api.name="Sub2API"',
    '-c', `model_providers.sub2api.base_url=${JSON.stringify(config.baseUrl)}`,
    '-c', 'model_providers.sub2api.env_key="SUB2API_API_KEY"',
    '-c', 'model_providers.sub2api.wire_api="responses"',
    '-c', 'model_providers.sub2api.requires_openai_auth=false',
  ] : ['--model', config.model];
  lines.push(`${windows ? '&' : 'exec'} ${config.client} ${args.map(quote).join(' ')} ${windows ? '@args' : '"$@"'}`);
  if (windows) lines.push('$clientExitCode = $LASTEXITCODE', '} finally {', "foreach ($name in $saved.Keys) { [Environment]::SetEnvironmentVariable($name, $saved[$name], 'Process') }", '}', 'exit $clientExitCode');
  return `${lines.join('\n')}\n`;
}

async function stat(filename) {
  try { return await fs.lstat(filename); } catch (error) { if (error.code === 'ENOENT') return undefined; throw error; }
}

async function guard(filename, directory = false) {
  const absolute = path.resolve(filename);
  const parent = path.dirname(absolute);
  if (parent !== absolute) await guard(parent, true);
  const info = await stat(absolute);
  if (info && (info.isSymbolicLink() || (directory ? !info.isDirectory() : !info.isFile()))) throw new Error(`Refusing a symbolic link or unexpected file type: ${absolute}`);
}

async function protect(directory) {
  await guard(directory, true);
  await fs.mkdir(directory, { recursive: true, mode: 0o700 });
  if (process.platform === 'win32') {
    const result = spawnSync('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command',
      "$ErrorActionPreference = 'Stop'; $acl = [System.Security.AccessControl.DirectorySecurity]::new(); $acl.SetAccessRuleProtection($true, $false); $sid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User; $rule = [System.Security.AccessControl.FileSystemAccessRule]::new($sid, 'FullControl', 'ContainerInherit,ObjectInherit', 'None', 'Allow'); $acl.AddAccessRule($rule); [IO.Directory]::SetAccessControl($env:SUB2API_ACL_DIRECTORY, $acl)",
    ], { env: { ...process.env, SUB2API_ACL_DIRECTORY: directory }, encoding: 'utf8', windowsHide: true });
    if (result.status !== 0) throw new Error(`Could not restrict the configuration directory ACL: ${result.stderr?.trim() || result.error?.code || result.status}`);
  } else await fs.chmod(directory, 0o700);
}

async function writePrivate(filename, value, executable = false) {
  await guard(filename);
  const temporary = `${filename}.${process.pid}.tmp`;
  await fs.writeFile(temporary, value, { flag: 'wx', mode: executable ? 0o700 : 0o600 });
  try { await fs.rename(temporary, filename); } finally { await fs.rm(temporary, { force: true }); }
}

export async function install(input, { directory, dryRun = false, restore = false } = {}) {
  const config = validateConfig(input);
  const root = path.resolve(directory);
  await guard(root, true);
  if (await stat(root)) {
    const managed = /^(?:codex|claude)(?:\.json|\.backup\.json|-sub2api\.(?:sh|ps1))$/;
    if ((await fs.readdir(root)).some(name => !managed.test(name))) throw new Error('Choose an empty directory or an existing Sub2API configuration directory.');
  }
  const filename = path.join(root, `${config.client}.json`);
  const backup = path.join(root, `${config.client}.backup.json`);
  const executable = path.join(root, `${config.client}-sub2api.${process.platform === 'win32' ? 'ps1' : 'sh'}`);
  for (const name of [filename, backup, executable]) await guard(name);
  const encoded = `${JSON.stringify(config, null, 2)}\n`;
  const old = await stat(filename) ? await fs.readFile(filename, 'utf8') : undefined;
  if (dryRun) return { executable, changed: old !== encoded, dryRun: true };
  await protect(root);
  if (old && old !== encoded && !restore) await writePrivate(backup, old);
  await writePrivate(executable, launcher(config, process.platform === 'win32'), true);
  await writePrivate(filename, encoded);
  return { executable, changed: old !== encoded, dryRun: false };
}

export async function main(args = process.argv.slice(2)) {
  if (Number(process.versions.node.split('.')[0]) < 22) throw new Error('Install Node.js 22 or newer first.');
  const values = new Map();
  const flags = new Set();
  for (let i = 0; i < args.length; i++) {
    if (['--dry-run', '--restore', '--test', '--help', '--no-model-fetch'].includes(args[i])) flags.add(args[i]);
    else if (['--client', '--base-url', '--model', '--directory'].includes(args[i]) && args[i + 1] && !args[i + 1].startsWith('--')) { values.set(args[i], args[i + 1]); i++; }
    else throw new Error('Unknown or incomplete option. Use --help.');
  }
  if (flags.has('--help')) {
    console.log(`Sub2API setup ${VERSION}\n--client codex|claude --base-url URL --model ID\n--dry-run (no writes or network) --restore (last backup)\n--test (a billable minimal inference request) --no-model-fetch\n--directory PATH (default: ~/.config/sub2api)\nAPI Key: hidden interactive prompt or SUB2API_SETUP_KEY environment variable.\nRequires an installed codex or claude command and Node.js 22+.`);
    return;
  }
  let muted = false;
  const output = new Writable({ write(chunk, encoding, callback) { if (!muted) process.stdout.write(chunk, encoding); callback(); } });
  const rl = createInterface({ input: process.stdin, output, terminal: Boolean(process.stdin.isTTY) });
  const ask = async (label, secret = false) => {
    if (!process.stdin.isTTY) throw new Error('Non-interactive setup requires --client, --base-url, --model and SUB2API_SETUP_KEY.');
    process.stdout.write(label);
    muted = secret;
    try { return (await rl.question('')).trim(); } finally { muted = false; if (secret) process.stdout.write('\n'); }
  };
  try {
    const client = values.get('--client') ?? await ask('Client (codex / claude): ');
    if (!['codex', 'claude'].includes(client)) throw new Error('Client must be codex or claude.');
    const directory = values.get('--directory') ?? path.join(os.homedir(), '.config', 'sub2api');
    let config;
    if (flags.has('--restore')) {
      const backup = path.resolve(directory, `${client}.backup.json`);
      await guard(backup);
      config = validateConfig(JSON.parse(await fs.readFile(backup, 'utf8')));
      if (config.client !== client) throw new Error('Backup client does not match.');
    } else {
      const defaultBase = `${DEFAULT_ORIGIN}${client === 'codex' ? '/v1' : ''}`;
      const baseUrl = values.get('--base-url') ?? (process.stdin.isTTY && !flags.has('--dry-run') ? await ask(`API base URL [${defaultBase}]: `) || defaultBase : defaultBase);
      const apiKey = flags.has('--dry-run') ? 'PREVIEW-ONLY' : process.env.SUB2API_SETUP_KEY ?? await ask('Sub2API API Key (hidden): ', true);
      // Validate destination before sending credentials to the models endpoint.
      config = validateConfig({ client, baseUrl, apiKey, model: values.get('--model') ?? 'model-placeholder' });
      let models = [];
      if (!flags.has('--dry-run') && !flags.has('--no-model-fetch')) {
        try {
          models = await listModels(config);
          console.log(models.length ? models.map((model, index) => `${index + 1}. ${model}`).join('\n') : 'No models returned. Enter a model ID from the console.');
        } catch { console.log('Model discovery failed. Check the URL, key and group, or enter the model ID from the console.'); }
      }
      let model = values.get('--model') ?? await ask('Model ID (or list number): ');
      if (/^\d+$/.test(model) && models[Number(model) - 1]) model = models[Number(model) - 1];
      config = validateConfig({ ...config, model });
    }
    const available = process.platform === 'win32'
      ? spawnSync('where.exe', [client], { stdio: 'ignore', windowsHide: true }).status === 0
      : spawnSync('which', [client], { stdio: 'ignore' }).status === 0;
    if (!available) console.log(`Install ${client} before using the generated launcher.`);
    console.log(`Client: ${config.client}\nAPI: ${config.baseUrl}\nModel: ${config.model}\nDirectory: ${path.resolve(directory)}\nCredential: ${flags.has('--dry-run') ? 'not requested' : 'stored in private config and launcher'}`);
    const result = await install(config, { directory, dryRun: flags.has('--dry-run'), restore: flags.has('--restore') });
    console.log(result.dryRun ? 'Preview complete; no files or network requests changed.' : `Ready: ${result.executable}\nRun this launcher from your project directory. Original client settings remain available.`);
    if (flags.has('--test') && !flags.has('--dry-run')) {
      console.log('Sending the requested minimal inference test (API usage may be charged).');
      await testRequest(config);
      console.log('Inference response received. Check the service usage log for accounting.');
    }
  } finally { rl.close(); }
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main().catch(error => { console.error(`Setup failed: ${error.code === 'ENOENT' ? 'File not found (a restore requires an existing backup).' : error.message}`); process.exitCode = 1; });
}
SUB2API_NODE_SOURCE
node "$setup_dir/setup.mjs" "$@"
